# Generated by Django 4.1.5 on 2023-06-01 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciertos', models.IntegerField()),
                ('realizado', models.BooleanField(default=False)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.encuesta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.user')),
            ],
            options={
                'unique_together': {('encuesta', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='Respuesta_correcta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('Encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('Respuesta_correcta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.respuesta_correcta')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.encuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.pregunta')),
                ('user', models.ManyToManyField(to='administrador.user')),
            ],
        ),
        migrations.AddField(
            model_name='encuesta',
            name='user',
            field=models.ManyToManyField(through='administrador.RespuestaUsuario', to='administrador.user'),
        ),
    ]
